### ISSUE TITLE
Testbed - invalid boolean parameters

### ISSUE THREAD

**Issue by xhorac19** [rysavy-ondrej/project-inventor#1]
When inputting a boolean into the schedule target parameters, the testbed is unable to parse/accept the input of that parameter.

Example 1:
```
monitors:
  - name: webapp.http
    module: webapp_http
    exec: src/webapp/webapp.http

schedule:
  - test: webapp.http
    write-to: webapp.http.vutbr
    targets:
      - { "target_url": "www.vut.cz", "timeout": 5, "follow_redirects": true }
    repeat-every: 5s
```
Return log:
```
testbed-webapp.http-1  |   Launching webapp.http.1, seconds since last run: 5.0177973, expected 5
testbed-webapp.http-1  | Traceback (most recent call last):
testbed-webapp.http-1  |   File "<string>", line 1, in <module>
testbed-webapp.http-1  | NameError: name 'true' is not defined
```
Example 2:
```
monitors:
  - name: webapp.http
    module: webapp_http
    exec: src/webapp/webapp.http

schedule:
  - test: webapp.http
    write-to: webapp.http.vutbr
    targets:
      - { "target_url": "www.vut.cz", "timeout": 5, "follow_redirects": "true" }
    repeat-every: 5s
```
Return log:
```
testbed-webapp.http-1  |   Launching webapp.http.1, seconds since last run: 5.0169817, expected 5
testbed-webapp.http-1  |   webapp.http.1 finished. Append results to ./results//webapp.http.vutbr.2025-03-17.json.
testbed-webapp.http-1  | ConvertFrom-Json: 
testbed-webapp.http-1  | Line |
testbed-webapp.http-1  |   11 |  …                $jsonObject = Get-Content $tempFile | ConvertFrom-Json
testbed-webapp.http-1  |      |                                                         ~~~~~~~~~~~~~~~~
testbed-webapp.http-1  |      | Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was attempted to be added to the existing key 'Server' was 'server'.
testbed-webapp.http-1  | Add-Member: 
testbed-webapp.http-1  | Line |
testbed-webapp.http-1  |   15 |  … sonObject | Add-Member -Name 'Timestamp' -Type NoteProperty -Value $t …
testbed-webapp.http-1  |      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testbed-webapp.http-1  |      | Cannot bind argument to parameter 'InputObject' because it is null.
testbed-webapp.http-1  |   webapp.http.1 finished. Append results to ./results//webapp.http.vutbr.2025-03-17.json.
```
In both examples, the returned result contains a null value.
