### ISSUE TITLE
Testbed - output verbosity idea

### ISSUE THREAD

**Issue by xhorac19** [rysavy-ondrej/project-inventor#2]
## The issue

Whenever a monitor returns an error message in the results, it may not have the original destination point in that message:
```
{"status":"error","error":{"error_code":"HTTP_MONITOR_ERROR","description":"Error running HTTP monitor: (35, 'TLS connect error: error:0A00006E:SSL routines::bad extension')"},"Timestamp":"2025-03-17T10:48:16"}
{"status":"error","error":{"error_code":"HTTP_MONITOR_ERROR","description":"Error running HTTP monitor: (16, 'Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.')"},"Timestamp":"2025-03-17T10:48:20"}
```
These entries cannot be associated with any of their original destinations. It would be beneficial to create a scheduler configuration that automatically inserts a custom string into the result, enabling us to associate these log messages by writing the destination into it. 

### Possible implementations

One way to do this is to include a separate field next to each target in `targets` fields, like so:
```
schedule:
  - test: webapp.http
    write-to: webapp.http.vutbr
    targets:
        - { "target_url": "https://www.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.vut.cz" }
        - { "target_url": "https://www.fce.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.fce.vut.cz" }
        - { "target_url": "https://www.fsi.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.fsi.vut.cz" }
        - { "target_url": "https://www.fekt.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.fekt.vut.cz" }
        - { "target_url": "https://www.fa.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.fa.vut.cz" }
        - { "target_url": "https://www.fch.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.fch.vut.cz" }
        - { "target_url": "https://www.favu.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.favu.vut.cz" }
        - { "target_url": "https://www.fit.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.fit.vut.cz" }
        - { "target_url": "https://www.cesa.vut.cz", "timeout": 5 }
          echo: { "target_url": "https://www.cesa.vut.cz" }
        - { "target_url": "https://www.caitec.cz", "timeout": 5 }
          echo: { "target_url": "https://www.caitec.cz" }
    hash-fields:
        - {"src": "body", "trg": "body_hash"}
    omit-fields:
        - "body"
    repeat-every: 5m
```

This would, however, almost double the size of the configuration and create a somewhat nasty redundancy.

Another way could be through the similar parametrized way that `hash-field` is already done:
```
schedule:
  - test: webapp.http
    write-to: webapp.http.vutbr
    targets:
        - { "target_url": "https://www.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.fce.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.fsi.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.fekt.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.fa.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.fch.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.favu.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.fit.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.cesa.vut.cz", "timeout": 5 }
        - { "target_url": "https://www.caitec.cz", "timeout": 5 }
    echo-fields:
        - {"src": "target_url", "trg": "original_url"}
    hash-fields:
        - {"src": "body", "trg": "body_hash"}
    omit-fields:
        - "body"
    repeat-every: 5m
```
The fields specified in `echo-fields` would be mirrored in the results. I think this second method would be a better way to address this issue. Still, I also imagine the first case may also be helpful in the future, as it may be beneficial to have a way to include some custom-defined messages that will be specified next to each target.
