### ISSUE TITLE
Access to the inner fields

### ISSUE THREAD

**Issue by rysavy-ondrej** [rysavy-ondrej/project-inventor#3]
For hashing and field omitting, support for innerfields (that is, the path expression field.field) should be supported.

**Comment by rysavy-ondrej** [comment]
The omit fields as well as hash fields can now be specified as path using dot notation:

```
 - test: dummy.test
    write-to: dummy-2
    omit-fields: [ "foo1", "bar", "xtra.prop2" ]  
    hash-fields: [ { src: "bar", trg: "bar-hash" }, { src : "xtra.prop1", trg : "xtra.prop1hash"} ] 
    targets:  
        - { "foo" : 1, "foo1" : 1, "foo2" : 1, "bar" : "abc", "xtra" : { "prop1" : "werkugherkthelrituh", "prop2" : 2234 } }
        - { "foo" : 2, "foo1" : 1, "foo2" : 1, "bar" : "def", "xtra" : { "prop1" : "werkugherkthelrituh", "prop2" : 2234 } }
        - { "foo" : 3, "foo1" : 1, "foo2" : 1, "bar" : "ghi", "xtra" : { "prop1" : "werkugherkthelrituh", "prop2" : 2234 } }
    repeat-every: 5s
```
